TLセキュリティ

* これなん
  TLが荒らされるのを防ごうという試みです。現在のところ以下のような機能を提供しています。

** 連投抑制
   著しく速い速度で連投しているユーザがいる場合、TLがそのユーザだけで埋まってしまいます。
   そのような場合、そのつぶやきには何ら有用性がないことが殆どなので、一定時間だけミュート状態にします。
   これは、mikutter本体のミュート機能とは独立しているので、ユーザが解除する方法はありません。
   mikutterを一旦終了すると、このミュート状態は解除されます。

* インストール方法
  まず、mikutterのバージョンが 0.0.4.526以降である必要があります。
  mikutter.rbがあるディレクトリにある plugin/ 以下か、 ~/.mikutter/plugin を作って、その中にこのプラグインを突っ込みます。
  例の通りのディレクトリ構成になるようにしてください

** 例
   - plugin/
     - tl_security/
       - README.org
       - tl_security.rb
* 使いかた
  インストールしたら動き出します。ユーザがミュートされた時、又は解除された時に、システムメッセージでお知らせします。

** 設定
   設定画面に「ファイアウォール」というタブが追加されるはずです。その中の数値を触ると、ミュートを開始する条件や、ミュート時間を設定できます。

* 注意
  名前からわかるとおり、ワクチンソフトとか、ファイアウォールみたいな、セキュリティソフトをイメージしています（そんな大層なものではないが）。
  つまり、最近のセキュリティソフトみたいに、入れてるだけでやたら重くなったり、バージョンアップのたびに10倍速くなったり、へたをするとかえってあなたのTwitterライフを脅かすことがあるかもしれない、というのは了承した上で使ってください。
  （具体的に言うと、リリースノートが誇大広告、設定によっては悪意のない人をミュートしてしまう等）

* カスタマイズ
  ほかに、こういうの迷惑だなと思うものがあったら、これを適当にカスタマイズしてもらえば、と思います。
  またそしたら、是非 pull request を送ってください。よさそうと思ったら取り込みます。
