TLセキュリティ

* これなん
  TLが荒らされるのを防ごうという試みです。現在のところ以下のような機能を提供しています。

** 連投抑制
   著しく速い速度で連投しているユーザがいる場合、TLがそのユーザだけで埋まってしまいます。
   そのような場合、そのつぶやきには何ら有用性がないことが殆どなので、一定時間だけミュート状態にします。
   これは、mikutter本体のミュート機能とは独立しているので、ユーザが解除する方法はありません。
   mikutterを一旦終了すると、このミュート状態は解除されます。

* インストール方法
  まず、mikutterのバージョンが 0.0.4.526以降である必要があります。
  mikutter.rbがあるディレクトリにある plugin/ 以下か、 ~/.mikutter/plugin を作って、その中にこのプラグインを突っ込みます。
  例の通りのディレクトリ構成になるようにしてください

** 例
   - plugin/
     - tl_security/
       - README.org
       - tl_security.rb
* 使いかた
  インストールしたら動き出します。ユーザがミュートされた時、又は解除された時に、システムメッセージでお知らせします。

** 設定
   設定のUIがなくてかなりアレです。
   以下の設定ができます。設定方法は、Alt+xをおしてから、
   | UserConfig[:設定名] = 値
   と入力して投稿ボタンをおしてください。
   また、現在の設定はAlt+xのあとで以下のように入力すると確認できます。
   | UserConfig[:設定名]

*** tl_security_update_section
   この秒数の間にtl_security_update_limit回ツイートがあれば一定時間ミュート。
   デフォルトは1秒

*** tl_security_update_limit
    この回数だけtl_security_update_section秒間の間にツイートがあれば一定時間ミュート
    デフォルトは5回

*** tl_security_mute_seconds
    一時ミュートする時間(秒)
    デフォルトは1800秒(30分)

*** 例
    一応、例としてデフォルト設定に戻すためのコードを書いておきます。
    | UserConfig[:tl_security_update_section] = 1
    | UserConfig[:tl_security_update_limit] = 5
    | UserConfig[:tl_security_mute_seconds] = 1800

* 注意
  名前からわかるとおり、ワクチンソフトとか、ファイアウォールみたいな、セキュリティソフトをイメージしています（そんな大層なものではないが）。
  つまり、最近のセキュリティソフトみたいに、入れてるだけでやたら重くなったり、バージョンアップのたびに10倍速くなったり、へたをするとかえってあなたのTwitterライフを脅かすことがあるかもしれない、というのは了承した上で使ってください。
  （具体的に言うと、リリースノートが誇大広告、設定によっては悪意のない人をミュートしてしまう等）

* カスタマイズ
  ほかに、こういうの迷惑だなと思うものがあったら、これを適当にカスタマイズしてもらえば、と思います。
  またそしたら、是非 pull request を送ってください。よさそうと思ったら取り込みます。
